//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LSports.Framework.Models.CustomClasses;

namespace LSports.Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public class FormTemplateCustomField
    {
        public int Id { get; set; }
        public int CustomFieldId { get; set; }
        public int SortOrder { get; set; }
        public int FormTemplateId { get; set; }
    
        public CustomField CustomField { get; set; }
        public FormTemplate FormTemplate { get; set; }
    }
}
