//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSports.Framework.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tic_UserDepartments
    {
        public int Id { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string UserId { get; set; }
        public string DepartmentRoleId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual tic_DepartmentRoles tic_DepartmentRoles { get; set; }
        public virtual tic_Departments tic_Departments { get; set; }
        public virtual user user { get; set; }
    }
}
