//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSports.Framework.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tic_CustomFields
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tic_CustomFields()
        {
            this.tic_FormTemplateCustomFields = new HashSet<tic_FormTemplateCustomFields>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Identifier { get; set; }
        public string PlaceholderText { get; set; }
        public int CustomeFieldTypeId { get; set; }
        public string DbTableName { get; set; }
        public string DbTableIdFieldName { get; set; }
        public string DbTableTextFieldName { get; set; }
        public string DbFilterFieldName { get; set; }
        public Nullable<int> StepNumber { get; set; }
        public Nullable<int> RootCustomFieldId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> DropdownCustomFieldId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tic_FormTemplateCustomFields> tic_FormTemplateCustomFields { get; set; }
        public virtual tic_CustomFieldTypes tic_CustomFieldTypes { get; set; }
    }
}
