//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSports.Framework.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tic_FormTemplateCustomFields
    {
        public int Id { get; set; }
        public int CustomFieldId { get; set; }
        public int SortOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UpdatedBy { get; set; }
        public int FormTemplateId { get; set; }
    
        public virtual tic_CustomFields tic_CustomFields { get; set; }
        public virtual tic_FormTemplates tic_FormTemplates { get; set; }
    }
}
