//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSports.Framework.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tic_TicketWorkflow
    {
        public int Id { get; set; }
        public Nullable<int> CustomerPriorityId { get; set; }
        public Nullable<int> TicketTypeId { get; set; }
        public Nullable<int> IssueTypeId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual tic_Departments tic_Departments { get; set; }
        public virtual tic_IssueTypes tic_IssueTypes { get; set; }
        public virtual tic_ProductCategories tic_ProductCategories { get; set; }
        public virtual tic_Products tic_Products { get; set; }
        public virtual tic_TicketTypes tic_TicketTypes { get; set; }
    }
}
