//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSports.Framework.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tic_TicketDefault
    {
        public int Id { get; set; }
        public int PriorityId { get; set; }
        public int TypeId { get; set; }
        public int ProductId { get; set; }
        public int IssueTypeId { get; set; }
        public int ProductCategoryId { get; set; }
        public string PackageId { get; set; }
    }
}
