//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSports.Framework.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketsLog
    {
        public int Id { get; set; }
        public int TicketId { get; set; }
        public Nullable<int> ActorId { get; set; }
        public int EntryTypeId { get; set; }
        public string EntryValue { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string EntryExtendedValue { get; set; }
        public string ActorUserId { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
