//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSports.Framework.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gb_ts_stagingEntities : DbContext
    {
        public gb_ts_stagingEntities()
            : base("name=gb_ts_stagingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<userclaim> userclaims { get; set; }
        public virtual DbSet<userlogin> userlogins { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<tic_DepartmentRoles> tic_DepartmentRoles { get; set; }
        public virtual DbSet<tic_Departments> tic_Departments { get; set; }
        public virtual DbSet<tic_EmailActions> tic_EmailActions { get; set; }
        public virtual DbSet<tic_EmailSendTo> tic_EmailSendTo { get; set; }
        public virtual DbSet<tic_EmailTemplate> tic_EmailTemplate { get; set; }
        public virtual DbSet<tic_EmailTemplateSendTo> tic_EmailTemplateSendTo { get; set; }
        public virtual DbSet<tic_Icons> tic_Icons { get; set; }
        public virtual DbSet<tic_IssueTypes> tic_IssueTypes { get; set; }
        public virtual DbSet<tic_TicketStatuses> tic_TicketStatuses { get; set; }
        public virtual DbSet<tic_TicketTypes> tic_TicketTypes { get; set; }
        public virtual DbSet<tic_UserDepartments> tic_UserDepartments { get; set; }
        public virtual DbSet<TicketField> TicketFields { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TicketsLog> TicketsLogs { get; set; }
        public virtual DbSet<tic_CustomFields> tic_CustomFields { get; set; }
        public virtual DbSet<tic_CustomFieldTypes> tic_CustomFieldTypes { get; set; }
        public virtual DbSet<tic_Files> tic_Files { get; set; }
        public virtual DbSet<tic_FormTemplateCustomFields> tic_FormTemplateCustomFields { get; set; }
        public virtual DbSet<tic_FormTemplates> tic_FormTemplates { get; set; }
        public virtual DbSet<tic_ProductCategories> tic_ProductCategories { get; set; }
        public virtual DbSet<tic_Products> tic_Products { get; set; }
        public virtual DbSet<tic_TicketWorkflow> tic_TicketWorkflow { get; set; }
        public virtual DbSet<CustomerContact> CustomerContacts { get; set; }
        public virtual DbSet<tic_TicketDefault> tic_TicketDefault { get; set; }
    }
}
